//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTL_ROLES
    {
        public CTL_ROLES()
        {
            this.CTL_USERS = new HashSet<CTL_USERS>();
        }
    
        public int IdRole { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<CTL_USERS> CTL_USERS { get; set; }
    }
}
