//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    
    public partial class UserGetById_Result3
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public string RoleName { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string SurName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string contrasena { get; set; }
        public Nullable<int> Parent { get; set; }
        public int Estatus { get; set; }
    }
}
